// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	newGame: (boardSize: number, komi: number | null, playerColor: string | null) => typedError<GameState, string>(__TAURI_INVOKE("new_game", { boardSize, komi: komi==null?komi:komi, playerColor })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	playMove: (row: number, col: number) => typedError<GameState, string>(__TAURI_INVOKE("play_move", { row, col })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	passTurn: () => typedError<GameState, string>(__TAURI_INVOKE("pass_turn")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	resign: () => typedError<[GameState, GameResult], string>(__TAURI_INVOKE("resign")).then((v) => ((v.status === "ok" ? { ...v, data: ([({...v.data[0],result:v.data[0].result==null?v.data[0].result:v.data[0].result}),v.data[1]]) } : v) as typeof v)),
	undoMove: () => typedError<GameState, string>(__TAURI_INVOKE("undo_move")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	listGames: () => typedError<SavedGame[], string>(__TAURI_INVOKE("list_games")),
	loadSavedGame: (gameId: number) => typedError<GameState, string>(__TAURI_INVOKE("load_saved_game", { gameId })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	getGamePosition: (moveNumber: number) => typedError<GameState, string>(__TAURI_INVOKE("get_game_position", { moveNumber })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	checkDifficultySuggestion: () => typedError<{
	direction: string,
	message: string,
} | null, string>(__TAURI_INVOKE("check_difficulty_suggestion")),
	getAiEngine: () => __TAURI_INVOKE<AiEngine>("get_ai_engine"),
	startEngine: () => typedError<KataGoStatus, string>(__TAURI_INVOKE("start_engine")),
	stopEngine: () => typedError<null, string>(__TAURI_INVOKE("stop_engine")),
	requestAiMove: () => typedError<GameState, string>(__TAURI_INVOKE("request_ai_move")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	getCoachingFeedback: () => typedError<{
	severity: Severity,
	error_class: ErrorClass | null,
	message: string,
	suggested_move: string | null,
	simplest_move: string | null,
	score_loss: number,
	move_number: number,
} | null, string>(__TAURI_INVOKE("get_coaching_feedback")).then((v) => ((v.status === "ok" ? { ...v, data: v.data==null?v.data:v.data } : v) as typeof v)),
	getSettings: () => typedError<Settings, string>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: Settings) => typedError<Settings, string>(__TAURI_INVOKE("update_settings", { settings })),
	saveGameSgf: () => typedError<string | null, string>(__TAURI_INVOKE("save_game_sgf")),
	loadGameSgf: () => typedError<{
	board_size: number,
	stones: StonePosition[],
	current_color: string,
	move_number: number,
	captures_black: number,
	captures_white: number,
	phase: GamePhase,
	result: GameResult | null,
	last_move: [number, number] | null,
	moves: MoveEntry[],
} | null, string>(__TAURI_INVOKE("load_game_sgf")).then((v) => ((v.status === "ok" ? { ...v, data: v.data==null?v.data:({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	startReview: (gameId: number | null) => typedError<null, string>(__TAURI_INVOKE("start_review", { gameId })),
	getReviewProgress: () => typedError<ReviewProgress, string>(__TAURI_INVOKE("get_review_progress")),
	getReviewData: () => typedError<ReviewData, string>(__TAURI_INVOKE("get_review_data")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,move_analyses:v.data.move_analyses.map(i=>i)}) } : v) as typeof v)),
	getReviewPosition: (moveNumber: number) => typedError<GameState, string>(__TAURI_INVOKE("get_review_position", { moveNumber })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,result:v.data.result==null?v.data.result:v.data.result}) } : v) as typeof v)),
	getOwnershipAt: (moveNumber: number) => typedError<number[] | null, string>(__TAURI_INVOKE("get_ownership_at", { moveNumber })).then((v) => ((v.status === "ok" ? { ...v, data: v.data==null?v.data:v.data.map(i=>i) } : v) as typeof v)),
	getReviewVariations: (moveNumber: number) => typedError<VariationMove[], string>(__TAURI_INVOKE("get_review_variations", { moveNumber })),
	getSkillProfile: () => typedError<SkillProfile, string>(__TAURI_INVOKE("get_skill_profile")),
	getSkillHistory: (windowDays: number | null) => typedError<SkillSnapshot[], string>(__TAURI_INVOKE("get_skill_history", { windowDays })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>i) } : v) as typeof v)),
	listProblems: (category: string | null, limit: number | null) => typedError<ProblemSummary[], string>(__TAURI_INVOKE("list_problems", { category, limit })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>({...i,difficulty:i.difficulty==null?i.difficulty:i.difficulty})) } : v) as typeof v)),
	startProblem: (problemId: number) => typedError<ProblemState, string>(__TAURI_INVOKE("start_problem", { problemId })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,board_state:({...v.data.board_state,result:v.data.board_state.result==null?v.data.board_state.result:v.data.board_state.result})}) } : v) as typeof v)),
	solveMove: (row: number, col: number) => typedError<SolveMoveResult, string>(__TAURI_INVOKE("solve_move", { row, col })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,board_state:({...v.data.board_state,result:v.data.board_state.result==null?v.data.board_state.result:v.data.board_state.result})}) } : v) as typeof v)),
	getHint: (level: string) => typedError<HintData, string>(__TAURI_INVOKE("get_hint", { level })),
	skipProblem: () => typedError<null, string>(__TAURI_INVOKE("skip_problem")),
	getProblemState: () => typedError<{
	problem_id: number,
	board_state: GameState,
	prompt: string,
	category: string,
	status: SolveStatus,
	hints_used: number,
	attempts: number,
	elapsed_seconds: number,
} | null, string>(__TAURI_INVOKE("get_problem_state")).then((v) => ((v.status === "ok" ? { ...v, data: v.data==null?v.data:({...v.data,board_state:({...v.data.board_state,result:v.data.board_state.result==null?v.data.board_state.result:v.data.board_state.result})}) } : v) as typeof v)),
	getRecommendedProblem: () => typedError<ProblemState, string>(__TAURI_INVOKE("get_recommended_problem")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,board_state:({...v.data.board_state,result:v.data.board_state.result==null?v.data.board_state.result:v.data.board_state.result})}) } : v) as typeof v)),
	getProblemStats: () => typedError<ProblemStats, string>(__TAURI_INVOKE("get_problem_stats")),
	generateProblemsFromGame: (threshold: number | null) => typedError<number, string>(__TAURI_INVOKE("generate_problems_from_game", { threshold: threshold==null?threshold:threshold })),
	importProblemsFromSgf: () => typedError<{
	imported: number,
	errors: string[],
} | null, string>(__TAURI_INVOKE("import_problems_from_sgf")),
	/**  Initialize the LLM model — downloads if needed, then loads into memory. */
	initLlmModel: () => typedError<string, string>(__TAURI_INVOKE("init_llm_model")),
	/**  Check the current LLM status. */
	getLlmStatus: () => typedError<string, string>(__TAURI_INVOKE("get_llm_status")),
	getDownloadStatus: () => __TAURI_INVOKE<DownloadStatus>("get_download_status"),
	retryDownloads: () => __TAURI_INVOKE<void>("retry_downloads"),
};

/* Types */
/**  Which opponent drives AI moves for the active game. */
export type AiEngine = "katago" | "practice_bot";

export type CategoryStat = {
	category: string,
	solved: number,
	attempted: number,
};

export type CoachingMessage = {
	severity: Severity,
	error_class: ErrorClass | null,
	message: string,
	suggested_move: string | null,
	simplest_move: string | null,
	score_loss: number,
	move_number: number,
};

export type Color = "Black" | "White";

export type DifficultySuggestion = {
	direction: string,
	message: string,
};

export type DownloadState = { state: "not_installed" } | { state: "downloading"; progress: number; phase: string } | { state: "ready" } | { state: "error"; message: string };

export type DownloadStatus = {
	katago: DownloadState,
	llm: DownloadState,
};

export type ErrorClass = "Direction" | "Shape" | "Reading" | "LifeAndDeath" | "Endgame" | "Opening" | "Ko" | "SenteGote";

export type GamePhase = "Playing" | "Finished";

export type GameResult = ({ Score: {
	winner: Color,
	margin: number,
} }) & { Resignation?: never } | ({ Resignation: {
	winner: Color,
} }) & { Score?: never } | "Draw";

/**  Serializable snapshot of game state for IPC. */
export type GameState = {
	board_size: number,
	stones: StonePosition[],
	current_color: string,
	move_number: number,
	captures_black: number,
	captures_white: number,
	phase: GamePhase,
	result: GameResult | null,
	last_move: [number, number] | null,
	moves: MoveEntry[],
};

export type HintData = { type: "None" } | { type: "Area"; min_row: number; max_row: number; min_col: number; max_col: number } | { type: "Candidates"; points: ([number, number])[] } | { type: "Answer"; point: [number, number] | null; message: string };

export type ImportProblemResult = {
	imported: number,
	errors: string[],
};

export type KataGoStatus = "ready" | "partial" | "not_installed";

export type MoveAnalysis = {
	move_number: number,
	/**  "black" | "white", None for initial position (move 0) */
	color: string | null,
	/**  GTP notation of the played move (None for initial position or pass) */
	player_move: string | null,
	/**  Win probability from Black's perspective, 0.0–1.0 */
	winrate_black: number,
	/**  Score lead from Black's perspective (positive = Black leads) */
	score_lead: number,
	/**  Engine's top choice in GTP notation */
	best_move: string | null,
	/**  Score loss in points (0.0 if best move or initial position) */
	score_loss: number,
	severity: Severity,
	coaching_message: string | null,
	/**  Principal variation from the engine */
	best_variation: string[],
};

export type MoveEntry = {
	move_number: number,
	color: string,
	row: number | null,
	col: number | null,
	is_pass: boolean,
};

export type MoveResult = { type: "Correct"; opponent_response: [number, number] | null; solved: boolean } | { type: "Wrong"; message: string };

export type ProblemState = {
	problem_id: number,
	board_state: GameState,
	prompt: string,
	category: string,
	status: SolveStatus,
	hints_used: number,
	attempts: number,
	elapsed_seconds: number,
};

export type ProblemStats = {
	total_solved: number,
	total_attempted: number,
	accuracy_percent: number,
	per_category: CategoryStat[],
};

export type ProblemSummary = {
	id: number,
	category: string | null,
	difficulty: number | null,
	prompt: string,
	board_size: number,
};

export type ReviewData = {
	board_size: number,
	total_moves: number,
	komi: number,
	move_analyses: MoveAnalysis[],
	/**  Up to 5 move numbers with significant score loss, sorted by move number. */
	top_mistakes: number[],
	status: ReviewStatus,
};

export type ReviewProgress = {
	total_positions: number,
	analyzed_positions: number,
	is_complete: boolean,
	status: ReviewStatus,
};

export type ReviewStatus = "Analyzing" | "Complete" | "Degraded" | "Failed";

export type SavedGame = {
	id: number,
	board_size: number,
	result: string,
	played_at: string,
};

export type Settings = {
	board_size: number,
	komi: number,
	show_coordinates: boolean,
	show_move_numbers: boolean,
	ai_strength: string,
	sound_enabled: boolean,
	feedback_timing: string,
	theme: string,
	onboarding_completed: boolean,
	experience_level: string,
};

export type Severity = "Excellent" | "Good" | "Inaccuracy" | "Mistake" | "Blunder";

export type SkillDimension = {
	mu: number,
	sigma: number,
};

export type SkillProfile = {
	overall_rank: number,
	reading: SkillDimension,
	shape: SkillDimension,
	direction: SkillDimension,
	endgame: SkillDimension,
	life_death: SkillDimension,
	fighting: SkillDimension,
	games_played: number,
	last_updated: string,
};

export type SkillSnapshot = {
	recorded_at: string,
	source: string,
	overall_rank: number,
	reading_mu: number,
	shape_mu: number,
	direction_mu: number,
	endgame_mu: number,
	life_death_mu: number,
	fighting_mu: number,
};

export type SolveMoveResult = {
	move_result: MoveResult,
	board_state: GameState,
	status: SolveStatus,
};

export type SolveStatus = "InProgress" | "Solved" | "Failed";

export type StonePosition = {
	row: number,
	col: number,
	color: string,
};

export type VariationMove = {
	row: number,
	col: number,
	color: string,
	comment: string | null,
	/**  Number of moves in this variation's continuation */
	continuation_length: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

