// Frontend-only types. Types that mirror Rust structs are generated by
// tauri-specta into ./bindings.ts — import them from there instead.

export type StoneColor = "black" | "white";

export type ThemeName = "study" | "grid";

export type NewGameConfig = {
  boardSize: number;
  playerColor: StoneColor;
  aiStrength: string;
};

export type LlmStatus = "not_installed" | "ready" | "loading" | "disabled";

// --- Event payloads (see ./events.ts; events are not covered by the generated bindings) ---

export type CoachingStreamChunk = {
  move_number: number;
  text_delta: string;
  is_complete: boolean;
};

export type LlmDownloadProgress = {
  downloaded: number;
  total: number;
};
